export { Service, layer, defaultLayer, type Interface } from "./service"
export { Embedder } from "./embedder"
export { VecStore } from "./vec-store"
export { buildFtsQuery } from "./fts-query"
export { parsePath, parseCcPath, buildPath, resolveProjectId, type Scope, type MemoryType, type MemoryLocator } from "./paths"
export { reconcileMemory, walkMemoryDir, walkCcRoot } from "./reconcile"
export { SemanticHash } from "./semantic-hash"
export { MemoryDecay } from "./memory-decay"
export { MemoryFtsTable } from "./fts.sql"
export { MemoryVecTable } from "./vec.sql"

export * as Memory from "./service"
